/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProjectsSlugApplicationsAreaRouteImport } from './routes/projects.$slug_.applications.$area'
import { Route as ProjectsSlugSystemCardRouteImport } from './routes/projects.$slug_.system.$card'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugApplicationsAreaRoute =
  ProjectsSlugApplicationsAreaRouteImport.update({
    id: '/projects/$slug_/applications/$area',
    path: '/projects/$slug/applications/$area',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsSlugSystemCardRoute = ProjectsSlugSystemCardRouteImport.update({
  id: '/projects/$slug_/system/$card',
  path: '/projects/$slug/system/$card',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/$slug/applications/$area': typeof ProjectsSlugApplicationsAreaRoute
  '/projects/$slug/system/$card': typeof ProjectsSlugSystemCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/$slug/applications/$area': typeof ProjectsSlugApplicationsAreaRoute
  '/projects/$slug/system/$card': typeof ProjectsSlugSystemCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/$slug_/applications/$area': typeof ProjectsSlugApplicationsAreaRoute
  '/projects/$slug_/system/$card': typeof ProjectsSlugSystemCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$slug'
    | '/projects/$slug/applications/$area'
    | '/projects/$slug/system/$card'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/$slug'
    | '/projects/$slug/applications/$area'
    | '/projects/$slug/system/$card'
  id:
    | '__root__'
    | '/'
    | '/projects/$slug'
    | '/projects/$slug_/applications/$area'
    | '/projects/$slug_/system/$card'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsSlugApplicationsAreaRoute: typeof ProjectsSlugApplicationsAreaRoute
  ProjectsSlugSystemCardRoute: typeof ProjectsSlugSystemCardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug_/applications/$area': {
      id: '/projects/$slug_/applications/$area'
      path: '/projects/$slug/applications/$area'
      fullPath: '/projects/$slug/applications/$area'
      preLoaderRoute: typeof ProjectsSlugApplicationsAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug_/system/$card': {
      id: '/projects/$slug_/system/$card'
      path: '/projects/$slug/system/$card'
      fullPath: '/projects/$slug/system/$card'
      preLoaderRoute: typeof ProjectsSlugSystemCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsSlugApplicationsAreaRoute: ProjectsSlugApplicationsAreaRoute,
  ProjectsSlugSystemCardRoute: ProjectsSlugSystemCardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
